# SConscript

Import('aEnv')

cppfiles = aEnv.Glob('*.cpp')

inc = ['../include', './', '../third_party']
usedlib = ['ga']
usedlibpath = ['../galgorithm']
aEnv.Library(target='syntax', source=cppfiles, CPPPATH=inc, LIBS=usedlib, LIBPATH=usedlibpath)
