# SConscript

Import('aEnv')

cppfiles = ['gensyntax.cpp', 'compilermake.cpp', 'compilersyntax.cpp', 'symbolmachine.cpp', 'prodfunction.cpp']
inc = ['../include', '../syntax', '../galgorithm', '../third_party']
usedlib = ['ga', 'syntax', 'typename']
usedlibpath = ['../syntax', '../galgorithm', '../thirty_party/typename']

aEnv.Library(target='mcompiler', source=cppfiles, CPPPATH=inc, LIBS=usedlib, LIBPATH=usedlibpath)
