# SConscript

Import('aEnv')

cppfiles = ['cplcompiler.cpp', 'expression-test-funcs.cpp']

inc = ['../include', '../syntax', '../compiler', '../makecompiler']
usedlib = ['compiler', 'syntax', 'mcompiler', 'regex']
usedlibpath = ['../syntax', '../compiler', '../mcompiler', '../third_party/regexlib']

aEnv.Library(target='cplcompiler', source=cppfiles, CPPPATH=inc, LIBS=usedlib, LIBPATH=usedlibpath)
